# Generated by Django 5.0.1 on 2024-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogplatfrm', '0002_blogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
